### ISSUE TITLE
Enhancement: Providing premature exit option for CLI 

### ISSUE THREAD

**Issue by carmen-chau** [moonsdust/street-whisper-app#10]
Look into whether implementing a feature where a user can prematurely exit the CLI prior to reaching the prompt that appears right before transcription/translation appears:

`Do you want to start the process? If not, this app will quit. `

Currently, if the user wishes to terminate CLI prior to this process, they would have to press CTRL-C 2-3 times to exit (the program also throws errors due to interrupted termination)

**Possible implementation ideas:**
- For each step in the CLI, have an exit option (ie: Add a "exit" option for each "choice" for each prompt). This would be extremely tedious to do, but I cannot think of better options (since at the moment, the CLI doesn't really allow spontaneous user input)

**Comment by carmen-chau** [comment]
@moonsdust thoughts about this issue? I think we should run it by the STREET team to see if this is a pressing issue to address, and how we can approach it.

**Comment by moonsdust** [comment]
> @moonsdust thoughts about this issue? I think we should run it by the STREET team to see if this is a pressing issue to address, and how we can approach it

@carmen-chau In the PR I made, I added in different ways the app can exit with throwing errors. But I had it so that for the list-type prompts, there's an option to exit the app and for the input-type prompts, users can just use CTRL-C to exit the app and it shouldn't throw an error (hopefully).
