### ISSUE TITLE
Bug: CLI doesn't give correct error message for invalid audio path inputs

### ISSUE THREAD

**Issue by carmen-chau** [moonsdust/street-whisper-app#14]
**General summary:** Need to properly handle error messages when user gives invalid audio path inputs and/or invalid destination paths.

**Case 1: When user types in invalid audio path**
_Note: Still need to double check whether the path is invalid as in: Invalid path on computer, or invalid because the file extension it refers to is invalid_

When a user types in an invalid audio path, followed by a valid destination path, the CLI just says "token does not exist" when re-prompting the user to try again. This is not the correct reason.

**Comment by moonsdust** [comment]
The script is pretty much running in a try except block. So that means that for any errors in receives from the script, it will return “Token Doesn’t Exist”. So because of this, you can check the error and have it print to the correct error statement instead of only “Token Doesn’t Exist”.

**Comment by carmen-chau** [comment]
@moonsdust Additional comment: Do you think it would be wise to truncate leading and trailing whitespace from an audio input path and the destination path, in case the user types an extra beginning or ending space by accident? IMO I think we should handle this case but wanna hear your thoughts

Having even 1 extra space by accident renders an invalid path so this fix might reduce the number of times a user needs to be reprompted

**Comment by moonsdust** [comment]
@carmen-chau I think we should do that with removing trailing and leading whitespace. I can implement that when working on the issue for spaces in the name

**Comment by carmen-chau** [comment]
Sure that sounds great, let me know if you need support with it!

> @carmen-chau I think we should do that with removing trailing and leading whitespace. I can implement that when working on the issue for spaces in the name
