### ISSUE TITLE
Minor corrections: Typo + clarification needed for token input

### ISSUE THREAD

**Issue by carmen-chau** [moonsdust/street-whisper-app#17]
3 minor issues flagged with respect to the token input in the CLI:

Bug 1: [RESOLVED]

Bug 2: This is an actual bug. If the user accidentally presses "ENTER" multiple times during the CLI's `What is your access token` prompt, the CLI will behave weirdly, and "skip" certain prompts. 

Eg:

<img width="1046" alt="Screenshot 2024-04-27 at 7 58 44 PM" src="https://github.com/moonsdust/street-whisper-app/assets/80921817/bf9f7e63-4bab-462b-a0ca-f7ba60c154ec">

Typo: There is a very minor typo in the CLI beginning instructions. "amd" should be corrected to "and" in the part: `If this is not your first time running the app amd have previously entered a valid token, you can just press enter on your keyboard.`

**Comment by moonsdust** [comment]
Bug 1 isn't a bug and it throws the invalid token error if you have never entered a correct access token before. I have tested it in the past when I haven't gotten an access token and it would throw an error if you enter any random string. But the tool should run as intended even if you put in a random string as the access token if you already inputted a valid access token in the past on that device

**Comment by carmen-chau** [comment]
> Bug 1 isn't a bug and it throws the invalid token error if you have never entered a correct access token before. I have tested it in the past when I haven't gotten an access token and it would throw an error if you enter any random string. But the tool should run as intended even if you put in a random string as the access token if you already inputted a valid access token in the past on that device

Ok that sounds great then, sorry that was a misunderstanding on my part. I'll mark that as resolved then!
