### ISSUE TITLE
Bug: "FileNotFoundError: [WinError 2] The system cannot find the file specified" error and other bugs on Windows

### ISSUE THREAD

**Issue by moonsdust** [moonsdust/street-whisper-app#36]
The following bugs were found on Windows: 
- [x] `FileNotFoundError: [WinError 2] The system cannot find the file specified` shows up when Whisper is detecting the language of the input file. 
- [x] Destination path contains "/" instead of "\\" for Windows 
- [x] Audio file name is not properly obtained

**Comment by moonsdust** [comment]
Possible solution to `FileNotFoundError: [WinError 2] The system cannot find the file specified`

https://stackoverflow.com/questions/74835362/i-am-getting-the-following-error-while-using-openais-whisper-ai-filenotfounde

**Comment by carmen-chau** [comment]
Another possible set of resources:

https://stackoverflow.com/questions/74959470/cant-use-openai-in-command-prompt

https://www.computerhope.com/issues/ch000549.htm

**Comment by moonsdust** [comment]
Solution (Based on: https://github.com/openai/whisper/discussions/109): 
- Download ffmpeg manually from https://ffmpeg.org/download.html (Specifically the Windows builds from gyan.dev) 
- Move the ffmpeg.exe file located in the folder you downloaded into your virtual environment's Scripts folder
